name: metrics

on:
  schedule: [{cron: "0 */1 * * *"}]
  workflow_dispatch:
  push:

env:
  IMAGE_BRANCH: ci-generated-metrics

jobs:
  metrics:
    runs-on: ubuntu-latest
    environment:
      name: metrics
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate metrics image
        uses: blanktiger/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories
          template: classic
          config_timezone: Europe/Warsaw
          config_order: base.header, base.activity+community, base.repositories, isocalendar, languages
          plugins_errors_fatal: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: javascript, html, css, scss, Jupyter Notebook, shell
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_indepth: no
          plugin_languages_recent_load: 300
          plugin_languages_recent_days: 14
          plugin_notable: no
          plugin_notable_repositories: no
